### ISSUE TITLE
Upgrade gRPC and remove futures compat code

### ISSUE THREAD

**Issue by nrc** [tikv/client-rust#148]
GRPC-rs now supports futures 0.3 so if we upgrade then we shouldn’t need the compatibility shims to go from 0.1 to 0.3.

**Comment by longfangsong** [comment]
> GRPC-rs now supports futures 0.3 so if we upgrade then we shouldn’t need the compatibility shims to go from 0.1 to 0.3.

I can have a try with this.
But maybe we should wait for grpc-rs bumping to 0.6.0.
As [this issue](https://github.com/tikv/grpc-rs/issues/462) mentioned, currently we need a patched compiler to make grpc-rs working with futures 0.3 and I cannot find a way to use this compiler without download it into the `client-rust` or `kvproto`'s dictionary, which is a very bad idea.

**Comment by nrc** [comment]
I think it is fine to use grpc-rs from Git for this. It would be good for us and for grpc-rs to get some experience using it before a proper release, and the rust client is not expected to be stable yet.

**Comment by longfangsong** [comment]
> I think it is fine to use grpc-rs from Git for this. It would be good for us and for grpc-rs to get some experience using it before a proper release, and the rust client is not expected to be stable yet.

After trying to use grpc-rs from Git, I found that the compiler would complains about "two different versions of crate `grpcio` are being used". This is because `kvproto` is using a different version of grpcio for now. 

But tikv also depends on `kvproto` (also used from git), and tikv might not be built succussfully if `kvproto`'s master branch change its dependency version. So maybe `kvproto` needs a new branch for this?

Anyway, I created a usable version of `client-rust` [here](https://github.com/longfangsong/client-rust/tree/remove-compact), with my own [fork](https://github.com/longfangsong/kvproto) of `kvproto`.

**Comment by nrc** [comment]
You can use a `patch` or `replace` section in Cargo.toml to propagate the dependency change to all the dependencies like kvproto. That should be much easier than forking. See the [cargo book](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html) for details.
